import Head from 'next/head'
import Maintenence from '@/components/common/maintenence'

export default function Home() {
  return (
    <>
      <Head>
        <title>GNI web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Maintenence />
    </>
  )
}
